services:
  app:
    image: ruby:3.2.2
    environment:
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_MASTER_KEY=2c035c9523f738e5b2590a43a18607d1
      - RAILS_SERVE_STATIC_FILES=true
      - DATABASE_URL=postgres://postgres:@db:5432/pizza_challenge
      - REDIS_URL=redis://redis:6379/1
      - BUNDLE_PATH=/bundle
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - ruby-bundle-cache:/bundle
    working_dir: /app
    command: >
      bash -c
      "
      rm -f /tmp/server.pid &&
      bin/setup &&
      bundle exec rails server -b 0.0.0.0 -P /tmp/server.pid
      "

  db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432'

  redis:
    image: "redis:7-alpine"
    ports:
      - 6379
    volumes:
      - ./tmp/redis_data:/var/lib/redis/data

volumes:
  ruby-bundle-cache:
    external: true
